/**
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then
add one more letter at a random position.
Find the letter that was added in t.
Example:
Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.
*/

const { findTheDifference } = require('./index');

describe('389. Find the Difference', () => {
  it('should return the different character', () => {
    const s = 'abcd';
    const t = 'abcde';
    const expected = 'e';

    const result = findTheDifference(s, t);
    expect(result).toBe(expected);
  });

  it('should return the different character', () => {
    const s = 'abcd';
    const t = 'dcbae';
    const expected = 'e';

    const result = findTheDifference(s, t);
    expect(result).toBe(expected);
  });

  it('should return the different character', () => {
    const s = 'a';
    const t = 'aa';
    const expected = 'a';

    const result = findTheDifference(s, t);
    expect(result).toBe(expected);
  });

  it('should return the different character', () => {
    const s = '';
    const t = 'a';
    const expected = 'a';

    const result = findTheDifference(s, t);
    expect(result).toBe(expected);
  });
});
